name: Linux Check
on:
  push:
    paths:
      - '.github/workflows/**'
      - '**/*.v'
      - 'build.vsh'
  pull_request:
    paths:
      - '.github/workflows/**'
      - '**/*.v'
      - 'build.vsh'
jobs:
  check:
    name: V vet & Test example
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install llama.cpp
        run: |
          sudo apt-get update
          sudo apt-get install -y libllama.cpp-dev
    
    # 复制库文件
    sudo cp llama_temp/libllama.so /usr/local/lib/
    sudo cp llama_temp/libggml.so /usr/local/lib/
    
    # 更新库缓存
    sudo ldconfig

      
      - name: Install V
        run: |
          git clone --depth=1 https://github.com/vlang/v
          cd v
          make
          sudo ./v symlink

      - name: Install v_llama_cpp
        run: v install.vsh

      - name: V vet
        run: v vet .

      - name: Run tests
        run: v run test/main.v

      - name: Unstall v_llama_cpp
        run: v uninstall.vsh
