name: Linux Check
on:
  push:
    paths:
      - '.github/workflows/**'
      - '**/*.v'
      - 'install.vsh'
      - 'uninstall.vsh'
  pull_request:
    paths:
      - '.github/workflows/**'
      - '**/*.v'
      - 'install.vsh'
      - 'uninstall.vsh'
jobs:
  check:
    name: V vet & Test example
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install llama.cpp
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git
          git clone --depth=1 https://github.com/ggml-org/llama.cpp /tmp/llama.cpp
          cmake -S /tmp/llama.cpp -B /tmp/llama.cpp/build \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=ON \
            -DLLAMA_BUILD_TESTS=OFF \
            -DLLAMA_BUILD_EXAMPLES=OFF \
            -DGGML_NATIVE=OFF
          cmake --build /tmp/llama.cpp/build --config Release --parallel 2
          sudo cmake --install /tmp/llama.cpp/build
          sudo ldconfig
    
      - name: Install V
        run: |
          git clone --depth=1 https://github.com/vlang/v /tmp/v
          cd /tmp/v
          make
          sudo ./v symlink

      - name: Install v_llama_cpp
        run: printf "1\n" | v install.vsh

      - name: V vet
        run: v vet .

      - name: Run tests
        run: v run test/main.v

      - name: Uninstall v_llama_cpp
        run: v uninstall.vsh
